#!/bin/bash
username1=$1
username2=$2
echo "$username1 :  Hi $username2"
echo  "$username2  : Hello $username1"
echo  "$username1 : How are you "
echo  "$username2  : Iam good"
echo  "$username1 : i want to tell something form long time"
echo  "$username2  : what is that"
echo  "$username1 : i love you"
echo  "$username2 : just shutup"