#!/bin/bash

echo "All variable passed :$@"
echo "Number of variables :$#"
echo "script name :$0"
echo "Present working directory :$PWD"
echo "Home Directory of current user :$HOME"
echo "which  user is running this script :$USER"
echo "process id of current scripot :$$"
sleep 60 & 
echo "process id of last command in backgroung :$!"
